/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _ReportsRoute } from '../pages/reports';
import { Route as _AboutRoute } from '../pages/about';
import { Route as _ExerciseUploadRoute } from '../pages/exercise-upload';
import { Route as _FoodUploadRoute } from '../pages/food-upload';
import { Route as _IndexRoute } from '../pages/';

declare module '@granite-js/react-native' {
  interface RegisterScreen {
    '/food-upload': ReturnType<typeof _FoodUploadRoute.useParams>;
    '/exercise-upload': ReturnType<typeof _ExerciseUploadRoute.useParams>;
    '/reports': ReturnType<typeof _ReportsRoute.useParams>;
    '/about': ReturnType<typeof _AboutRoute.useParams>;
    '/': ReturnType<typeof _IndexRoute.useParams>;
  }
}
