import type { Route as _IndexRoute } from '../pages';
import type { Route as _AboutRoute } from '../pages/About';
import type { Route as _ExerciseUploadRoute } from '../pages/ExerciseUpload';
import type { Route as _FoodUploadRoute } from '../pages/FoodUpload';
import type { Route as _LoginRoute } from '../pages/Login';
/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import type { Route as _ReportsRoute } from '../pages/Reports';

declare module '@granite-js/react-native' {
  interface RegisterScreen {
    '/food-upload': ReturnType<typeof _FoodUploadRoute.useParams>;
    '/exercise-upload': ReturnType<typeof _ExerciseUploadRoute.useParams>;
    '/reports': ReturnType<typeof _ReportsRoute.useParams>;
    '/about': ReturnType<typeof _AboutRoute.useParams>;
    '/login': ReturnType<typeof _LoginRoute.useParams>;
    '/': ReturnType<typeof _IndexRoute.useParams>;
  }
}
